# AggressiveAnimals configuration
#
# Note: This configuration file is significantly different from the one provided by Michielcx in the
# original AggressiveAnimals.

# AggressiveAnimals does not rewrite the configuration files if they exist, so changes must be made
# manually. Undefined configuration nodes default to the values found in the original comments (for
# sanity, it would be wise not to edit them). The default values will be adequate in many cases, so
# configuration for additional mob-types can be very simple -- for example:
# --------------------
# axolotl:
#   enabled: true
# --------------------
# is all that is required; the remaining configuration options will use default values.

# ========== CHECK FOR UPDATES =====================================================================
# If you do not want notification of available updates in the console log, you may disable it here.
check-for-updates: true

# ========== BSTATS METRICS ========================================================================
# By default, the plugin collects and transmits anonymous statistics to bstats.org.
# Data collection may be disabled here, or generally in the bStats/config.yml.
#
enable-metrics: true

# ========== PER MOB ATTACK PROFILES ===============================================================
# An attack profile must be created for each mob-type that you want to stage attacks.
# Only the enabled node is required. Undefined nodes use default values.
#
# mob-type:
#   enabled: true                      If true, this mob-type should engage in attacks against players
#   always-aggressive: false           If true, mobs should attack only in retaliation for player attack
#   speed-multiplier: 1.0              Multiple of vanilla movement speed (examples: 1.0 is regular speed, 0.5 is half speed, 2.0 is double speed)
#   attack-damage: 1.0                 Damage inflicted on the target on each attack (in half-hearts)
#   attack-damage-limit: 2             The attacker will leave the target alive with the specified amount of health (in half hearts)
#   attack-speed: 20                   Frequency of attack, same as vanilla except for zombies (in ticks)
#   attack-range: 1                    Distance at which the mob can damage the player (in blocks)
#   attack-leap-height: 0.0            Height attacker may leap when attacking (in blocks; 0.0 or below means disabled)
#   acquisition-range: 16              Distance at which the attaker can detect a target
#   deacquisition-range: 20            Distance at which the victim can escape attack
#   attacker-health-threshold: 5       Attack should stop when the health of the attacker falls below the threshold (in half-hearts)
#   age:                               Attacks may be waged by adults and/or babies
#     adult: true                      If true, adult mobs should attack
#     baby: false                      If true, baby mobs should attack
#   ignore-npcs: true                  If true, ignore NPCs created by NPC managers, such as Citizens, EliteMobs, InfernalMobs, and Shopkeepers
#   named-mobs-only: false             If true, only named mobs may attack
#   override-targeting: false          If true, remove vanilla targeting behavior and use only attack-conditions; useful for hostile mob-types
#   group-aggression-range: 20         If other mobs of the same type are within range of the attacker, they should join the attack (in blocks)
#   player-movement:                   Mob should attack if the player is
#     standing: true
#     sneaking: true
#     walking: true
#     sprinting: true
#     looking: true                    Like locking eyes with an Enderman
#     sleeping: true
#     gliding: true
#   enabled-worlds: []                 Worlds in which attacks by this mob-type is enabled; if empty, it is enabled in all worlds
#   disabled-worlds:                   Worlds in which attacks by this mob-type is disabled; must be set explicitly; takes precedence over enabled_worlds
#     - "world_example"

mobs:
  chicken:
    enabled: true
    always-aggressive: false
    speed-multiplier: 1.0
    attack-damage: 1.0
    attack-damage-limit: 2
    attack-speed: 20
    attack-range: 1
    attack-leap-height: 0.0
    acquisition-range: 16
    deacquisition-range: 20
    attacker-health-threshold: 5
    age:
      adult: true
      baby: false
    ignore-npcs: true
    named-mobs-only: false
    override-targeting: false
    group-aggression-range: 20
    player-movement:
      standing: true
      sneaking: true
      walking: true
      sprinting: true
      looking: true
      sleeping: true
      gliding: true
    enabled-worlds: []
    disabled-worlds:
      - "world_example"

# Additional passive mob-types. Missing parameters will use defaults.
  axolotl:
    enabled: false
    attack-leap-height: 0.3
  bat:
    enabled: false
  cat:
    enabled: false
    attack-leap-height: 0.3
  cod:
    enabled: false
  cow:
    enabled: false
  donkey:
    enabled: false
  fox:
    enabled: false
    attack-leap-height: 0.3
  frog:
    enabled: false
  glow_squid:
    enabled: false
  horse:
    enabled: false
  mooshroom:
    enabled: false
  mule:
    enabled: false
  ocelot:
    enabled: false
    attack-leap-height: 0.3
  parrot:
    enabled: false
  pig:
    enabled: false
  pufferfish:
    enabled: false
  rabbit:
    enabled: false
    attack-leap-height: 0.3
  salmon:
    enabled: false
  sheep:
    enabled: false
  skeleton_horse:
    enabled: false
  snow_golem:
    enabled: false
  squid:
    enabled: false
  strider:
    enabled: false
  tadpole:
    enabled: false
  tropical_fish:
    enabled: false
  turtle:
    enabled: false
  villager:
    enabled: false
  wandering_trader:
    enabled: false
