name: ${project.name}
version: ${project.version}
api-version: 1.18
main: ${project.groupId}.${project.artifactId}.${project.name}
description: ${project.description}
softdepend: [Citizens, EliteMobs, InfernalMobs, Shopkeepers]
authors:
  - drives_a_ford
  - SlimeDog
commands:
  aggressiveanimals:
    usage: /<command>
    description: Main command for plugin (allowing one to reload its state)
    permissions: aggressiveanimals.command
    aliases: [aggro]

permissions:
  aggressiveanimals.command:
    description: Allows using the command
    default: op
  aggressiveanimals.reload:
    description: Allows reloading the plugin
    default: op
  aggressiveanimals.list:
    description: Allows showing list of aggressive animals
    default: op
  aggressiveanimals.info:
    description: Allows showing info regarrding a specific mob type
    default: op
